#ifndef BB_GINI_VERSION_H_
#define BB_GINI_VERSION_H_

#define BB_GINI_VERSION "0.1.0"

#define BB_GINI_MAJOR_VERSION 0
#define BB_GINI_MINOR_VERSION 1
#define BB_GINI_PATCH_VERSION 0

#endif  // BB_GINI_VERSION_H_

